services:

  auth-api:
    build:
      context: ./Smart-Solutions-Auth-API
    container_name: smart-auth-api
    environment:
      JWT_SECRET: mi-clave # Cambiar
    ports:
      - "8081:8081"
    networks:
      - smart-network

  gateway-api:
    build:
      context: ./Smart-Solutions-Gateway-API
    container_name: smart-gateway-api
    environment:
      JWT_SECRET: mi-clave # Cambiar 
    ports:
      - "8080:8080"
    depends_on:
      - auth-api
    networks:
      - smart-network

networks:
  smart-network:
    driver: bridge